# Generated by Django 6.1.1 on 2026-10-03 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('publisher', models.CharField(max_length=150)),
                ('developer', models.CharField(max_length=150)),
                ('release_year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('cover_image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('PLAYSTATION', 'PlayStation'), ('XBOX', 'Xbox'), ('NINTENDO', 'Nintendo')], max_length=20)),
                ('generation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(choices=[('REG1', 'Region 1 (US)'), ('REG2', 'Region 2 (EU/UK)'), ('REG3', 'Region 3 (Asia/Indo)'), ('ALL', 'Region All')], default='REG3', max_length=10)),
                ('condition', models.CharField(choices=[('SEALED', 'Brand New Sealed'), ('PREOWNED', 'Pre-owned / Bekas')], default='SEALED', max_length=10)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('weight_grams', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_variants', to='catalog.platform')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'platform', 'region', 'condition'), name='unique_game_platform_region_condition')],
            },
        ),
    ]
