# Generated by Django 6.1.1 on 2026-10-03 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Sudah Dibayar'), ('SHIPPED', 'Sedang Dikirim'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], db_index=True, default='PENDING', max_length=20)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
                ('subdistrict_id', models.CharField(max_length=50)),
                ('courier_name', models.CharField(max_length=50)),
                ('courier_service', models.CharField(max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_weight_grams', models.PositiveIntegerField(default=120)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snap_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.gamevariant')),
            ],
        ),
    ]
